# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0009_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnersdetails',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='partnersdetails',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
