# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0010_auto_20170807_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnersdetails',
            name='address',
        ),
        migrations.AlterField(
            model_name='partnersdetails',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=13.0693308, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='partnersdetails',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=77.6170964, max_digits=9, null=True),
        ),
    ]
