# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0011_auto_20170807_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnersdetails',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='partnersdetails',
            name='longitude',
        ),
        migrations.AddField(
            model_name='partnersdetails',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
    ]
