# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0014_auto_20170808_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnersdetails',
            name='status',
            field=models.CharField(choices=[('select', 'SELECT'), ('A', 'Active'), ('I', 'Inactive')], default='select', max_length=20),
        ),
    ]
